# This is a basic workflow that is manually triggered

name: ğŸ“± Manual Build APKs (dev or prod)

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      flavor:
        description: 'Â¿QuÃ© apk deseas compilar?'
        required: true
        default: 'dev'
        type: choice
        options: 
          - dev
          - prod

jobs:
  build-apks:
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v4

      - name: ğŸ¦ Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.6'

      - name: ğŸ“„ Create env files
        run: |
          echo "BASE_API=https://fake.api" > .env
          echo "BASE_API=https://fake.api" > test/.env

      - name: ğŸ“¦ Install dependencies
        run: flutter pub get

      # --- Build APK ---
      - name: ğŸ—ï¸ Build APK
        run: flutter build apk --flavor ${{ github.event.inputs.flavor }} -t lib/main_${{ github.event.inputs.flavor }}.dart

      # --- Upload artifacts ---
      - name: ğŸ“¤ Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apks
          path: task_notes_app/build/app/outputs/flutter-apk/*.apk
