# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: task_notes_app

    steps:
      - name: â¬‡ï¸ Checkout
        uses: actions/checkout@v4

      - name: ðŸ¦ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.6'

      - name: ðŸ“„ Create env files
        run: |
          echo "BASE_API=https://fake.api" > .env
          echo "BASE_API=https://fake.api" > test/.env
    
      - name: ðŸ“¥ Install dependencies
        run: flutter pub get

      - name: ðŸ“Š Analyze project source
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

      - name: ðŸ§ª Run tests
        run: flutter test --coverage

      - name: ðŸ§° Install lcov (genhtml)
        run: sudo apt-get update && sudo apt-get install -y lcov

      - name: ðŸ“¦ Generate HTML report from lcov
        run: genhtml coverage/lcov.info -o coverage/html

      - name: ðŸ—‚ Prepare site root
        run: |
          mkdir -p site/coverage
          cp -r coverage/html/* site/coverage
          touch site/.nojekyll
          cat > site/index.html <<'EOF'
          <!doctype html>
          <meta charset="utf-8">
          <meta http-equiv="refresh" content="0; URL=coverage/index.html">
          <title>Coverage</title>
          <a href="coverage/index.html">Ir al reporte de cobertura</a>
          EOF
        
      - name: ðŸš€ Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: site
